from pathlib import Path
import subprocess,json,shutil
r=Path('/Users/jlee/Documents/Dev/source/myNextSeason');p=r/'autoShorts/episodes/google-messages-keep-user-edit';out=Path('/Users/jlee/Documents/ChatGPT/ba/output/keep-hybrid');A=r/'output/28-google-messages-keep/codex_final_send.mp4';bg=r/'autoShorts/episodes/google-messages-keep/audio/ambient-original.wav'
def run(args):subprocess.run(['ffmpeg','-y','-v','error',*args],check=True)
run(['-i',str(p/'renders/s01.mp4'),'-i',str(p/'audio/s01.mp3'),'-i',str(bg),'-filter_complex','[1:a]aresample=48000,adelay=120:all=1,apad=whole_len=316800,atrim=end_sample=316800,asetpts=N/SR/TB,asplit=2[n][sc];[2:a]atrim=duration=6.6,asetpts=PTS-STARTPTS,volume=0.7[b];[b][sc]sidechaincompress=threshold=0.025:ratio=5:attack=15:release=250[d];[n][d]amix=inputs=2:duration=first:normalize=0,loudnorm=I=-18:TP=-2:LRA=9,volume=2dB[a]','-map','0:v','-map','[a]','-t','6.6','-c:v','copy','-c:a','aac','-b:a','192k','-ar','48000',str(out/'intro.mp4')])
run(['-i',str(out/'intro.mp4'),'-i',str(A),'-filter_complex','[0:v]fps=30,setsar=1,setpts=PTS-STARTPTS[v0];[1:v]fps=30,setsar=1,setpts=PTS-STARTPTS[v1];[0:a]aresample=48000,aformat=channel_layouts=stereo,apad=whole_len=316800,atrim=end_sample=316800,asetpts=N/SR/TB[a0];[1:a]aresample=48000,aformat=channel_layouts=stereo,atrim=duration=38.866667,asetpts=PTS-STARTPTS[a1];[v0][a0][v1][a1]concat=n=2:v=1:a=1[v][a]','-map','[v]','-map','[a]','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-r','30','-c:a','aac','-b:a','192k','-movflags','+faststart',str(out/'couple_keep_Bintro_Astyle_final.mp4')])
run(['-ss','3','-i',str(out/'couple_keep_Bintro_Astyle_final.mp4'),'-frames:v','1','-q:v','2',str(out/'thumbnail.jpg')])
dest=r/'output/28-google-messages-keep';shutil.copy2(out/'couple_keep_Bintro_Astyle_final.mp4',dest/'codex_hybrid_Bintro_Astyle.mp4');shutil.copy2(out/'thumbnail.jpg',dest/'codex_hybrid_Bintro_Astyle_thumb.jpg')
(out/'edit-notes.json').write_text(json.dumps({'edit':'B first scene restyled with A typography, palette, bubbles, then entire A','introSeconds':6.6,'baseASec':38.866667,'generatedImage':'builtin image_gen removed typography from B frame preserving couple','AOriginalPreserved':str(A)},ensure_ascii=False,indent=2));print(out/'couple_keep_Bintro_Astyle_final.mp4')
