from pathlib import Path
import json,shutil,subprocess
r=Path('/Users/jlee/Documents/Dev/source/myNextSeason');a=r/'autoShorts';p=a/'episodes/google-messages-keep-user-edit';e=json.loads((p/'episode.json').read_text());s=e['scenes'][0];s['timing'].update(start=0,duration=6.6,speechEnd=6.274807);s['timing']['words']=[{**w,'start':w['start']+.12,'end':w['end']+.12} for w in json.loads((p/'audio/s01.json').read_text())['words']];e['transitionSeconds']=0;s['onScreen']['showCaptions']=False;(p/'episode.json').write_text(json.dumps(e,ensure_ascii=False,indent=2));subprocess.run(['node','scripts/build-scenes.js',e['slug']],cwd=a,check=True)
(p/'media').mkdir(exist_ok=True);shutil.copy2('/Users/jlee/.codex/generated_images/01a0ebac-aac9-7e70-9377-62ab4ec1199e/exec-98cb8a2d-dc2b-49c6-8ef6-cd8c83d2d2c2.png',p/'media/intro-clean.png');shutil.copy2(r/'flow-pipeline/fonts/Pretendard-Bold.ttf',p/'vendor/Pretendard-Bold.ttf')
base=(a/'templates/scenes/_base.html').read_text().replace('"Pretendard", "Apple SD Gothic Neo", "Noto Sans KR", system-ui, sans-serif','Keep, sans-serif')
css='''@font-face{font-family:Keep;src:url('vendor/Pretendard-Bold.ttf')}#root{font-family:Keep}.stage{inset:0;display:block}.glow,.progress,.captions{display:none}.photo{position:absolute;left:0;top:150px;width:1080px;height:1920px;object-fit:cover}.wash{position:absolute;inset:0;background:linear-gradient(0deg,#faf4e8 9%,#faf4e8dc 23%,transparent 50%,#faf4e800 70%,#faf4e8cc 89%)}.eyebrow{position:absolute;top:300px;left:72px;background:#faf4e8ed;border-radius:12px;padding:8px 14px;font-size:27px;letter-spacing:2px}.title{position:absolute;left:70px;top:370px;font-size:72px;line-height:1.13;color:#102849;letter-spacing:-3px}.bubble{position:absolute;left:70px;top:1140px;background:#ffdc6c;color:#102849;border-radius:28px;padding:25px 34px;font-size:49px;box-shadow:0 10px 0 #10284912}.reply{left:270px;right:140px;top:1255px;background:#102849;color:#faf4e8;font-size:45px}.bridge{position:absolute;top:1400px;left:75px;font-size:35px;color:#102849}.note{position:absolute;top:1515px;left:73px;font-size:25px;color:#536174}'''
content='<div class="eyebrow">GOOGLE 메시지 × KEEP</div><div class="title">우유 샀어?<br>또 물어봤다면</div><div class="bubble ask">우유 샀어?</div><div class="bubble reply">아, 나도 샀는데…</div><div class="bridge">장보기 전에, 같은 목록부터</div><div class="note">AI 생성 장면 · 설명용 그림</div>'
js='stage.innerHTML='+json.dumps(content,ensure_ascii=False)+';'
js+="tl.fromTo('.photo',{scale:1},{scale:1.025,duration:6.6,ease:'none'},0);tl.fromTo('.ask',{opacity:0,y:18},{opacity:1,y:0,duration:.25,ease:'power3.out'},.17);tl.fromTo('.reply',{opacity:0,y:18},{opacity:1,y:0,duration:.25,ease:'power3.out'},1.33);tl.fromTo('.bridge',{opacity:0,y:10},{opacity:1,y:0,duration:.3},3.35);"
vals={**e['theme'],'id':'s01','renderDuration':'6.6','marker':'autoshorts:custom B-intro-in-A-style','sceneJson':json.dumps({'id':'s01','onScreen':s['onScreen'],'showCaptions':False,'words':s['timing']['words'],'speechEnd':6.274807,'duration':6.6,'renderDuration':6.6,'globalStart':0,'total':6.6},ensure_ascii=False),'templateStyle':css,'templateScript':js,'bgLayer':'<img class="photo" src="media/intro-clean.png"><div class="wash"></div>'}
for k,v in vals.items():base=base.replace('{{'+k+'}}',v)
(p/'scenes/s01.html').write_text(base)
