const fs=require('fs'),path=require('path');
const root='/Users/jlee/Documents/Dev/source/myNextSeason';const ep=root+'/autoShorts/episodes/postmeal-walk';
const puppeteer=require(root+'/autoShorts/node_modules/puppeteer-core');
const dir=ep+'/cards';fs.mkdirSync(dir+'/src',{recursive:true});
const base=`<style>@font-face{font-family:P;src:url('${ep}/vendor/Pretendard-Bold.ttf')}*{box-sizing:border-box}body{margin:0;width:1080px;height:1080px;background:#f5f0e8;color:#273c31;font-family:P}main{padding:80px;height:1080px;position:relative;overflow:hidden}small{font-size:22px;letter-spacing:3px;color:#78816c}h1{font-size:72px;line-height:1.16;margin:50px 0 35px;letter-spacing:-3px}p{font-size:31px;line-height:1.55;margin:25px 0}.foot{position:absolute;bottom:65px;font-size:21px;color:#78816c}.box{padding:32px;border-radius:25px;background:#e2e6d7;margin-top:24px}.num{font-size:115px;line-height:1.2;color:#657a48}.row{display:flex;gap:18px;margin-top:65px}.tile{flex:1;background:#e2e6d7;border-radius:80px 80px 20px 20px;text-align:center;padding:32px 12px}.tile p{font-size:26px}img{object-fit:cover}.photo{position:absolute;right:0;bottom:0;width:590px;height:740px;object-position:50% 36%;mask-image:linear-gradient(to right,transparent,black 35%)}.text{position:relative;z-index:2}</style>`;
const pages=[
`<img class="photo" src="${ep}/media/meal.png"><div class="text"><small>WALK / AFTER MEALS</small><h1>몇 분 걸으면<br>혈당이 내려갈까?</h1><p>식후 걷기의 원리와 연구</p><div class="box" style="width:420px;margin-top:80px"><span class="num">10분</span><p>매 끼니 뒤 걷기를<br>연구했습니다.</p></div></div>`,
`<small>SCIENCE / 01</small><h1>움직이는 근육은<br>포도당을 씁니다</h1><div class="box"><p>걷는 동안 근육이 수축하면<br>혈액 속 포도당을 흡수해<br>에너지로 이용합니다.</p></div><div class="row"><div class="tile"><p>혈액 속<br>포도당</p></div><div style="font-size:70px;align-self:center">→</div><div class="tile"><p>근육의<br>에너지 이용</p></div></div><p style="font-size:24px;color:#78816c">원리 설명용 도식 · 출처: 미국당뇨병학회(ADA)</p>`,
`<small>EVIDENCE / 02</small><h1>같은 30분,<br>식사 뒤 나눠 걷기</h1><p>제2형 당뇨병 성인 41명 · 각 조건 2주</p><div class="box"><p>하루 30분 걷기 vs 매 끼니 뒤 10분</p><span class="num">약 12% ↓</span><p>식후 혈당 상승의 누적 지표(iAUC)</p></div><p style="font-size:27px">혈당 농도 자체가 12% 감소했다는 뜻은 아닙니다.<br>식후 3시간 iAUC 기하평균비 0.88.<br>Reynolds et al., Diabetologia (2016)</p>`,
`<small>KEEP IT COMFORTABLE / 04</small><h1>정상화 보장보다,<br>꾸준한 작은 습관</h1><div class="box"><p>식사 뒤 편안한 속도로 짧게 걸어보세요.</p></div><div class="box"><p>10분 만에 정상화되는 것은 아닙니다.<br>효과는 사람마다 다릅니다.</p></div><div class="box" style="background:#ebe3ce"><p>인슐린·일부 당뇨약을 쓴다면<br>저혈당 예방 방법을 의료진과 확인하세요.</p></div>`];
(async()=>{const browser=await puppeteer.launch({executablePath:'/Users/jlee/.cache/hyperframes/chrome/chrome-headless-shell/mac_arm-152.0.7977.30/chrome-headless-shell-mac-arm64/chrome-headless-shell',headless:true,args:['--no-sandbox','--allow-file-access-from-files']});const page=await browser.newPage();await page.setViewport({width:1080,height:1080,deviceScaleFactor:1});for(let i=0;i<pages.length;i++){let n=String(i+1).padStart(2,'0'),f=dir+'/src/'+n+'.html';fs.writeFileSync(f,`<!doctype html><meta charset="utf-8">${base}<main>${pages[i]}<div class="foot">식후 걷기 · 작은 습관의 힘 <span style="margin-left:240px">${n} / 04</span></div></main>`);await page.goto('file://'+f);await page.evaluate(async()=>{await document.fonts.ready;return true});await page.screenshot({path:dir+'/'+n+'.png'});}await browser.close();fs.mkdirSync(root+'/output/20-postmeal-walk/cards',{recursive:true});for(let i=1;i<=4;i++){const n=String(i).padStart(2,'0');fs.copyFileSync(dir+'/'+n+'.png',root+'/output/20-postmeal-walk/cards/'+n+'.png');}fs.copyFileSync(__filename,ep+'/scripts/walk-cards.cjs');console.log('4 cards complete');})();
